### ISSUE TITLE
我是centos7   提示我的glibc版本低了

### ISSUE THREAD

**Issue by chz2008** [P001water/yuze#2]
![图片](https://github.com/P001water/yuze/assets/41458106/80493217-bb46-4229-8734-ee218fabfdd9)
能否提供一个兼容版本？另外，你这个linux版本的怎么编译的。2.34的版本  很高。

[root@VM centos ~]# ./yuze_for_linux_x64 -m yuze_listen -s 7878 -e 9999
./yuze_for_linux_x64: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./yuze_for_linux_x64)
[root@VM centos ~]# ldd --version | grep libc
ldd (GNU libc) 2.17

**Comment by P001water** [comment]
vistual studio remote dev在我的kali上编译的，回头整个makefile传上来
